apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  labels:
    app: blog-backend
spec:
  selector:
    matchLabels:
      app: blog-backend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: blog-backend
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "database"
        vault.hashicorp.com/agent-inject-secret-dotenv: "blog-dev/data/app"
        vault.hashicorp.com/agent-inject-template-dotenv: |
          {{- with secret "blog-dev/data/app" -}}
          export SPRING_DATASOURCE_URL="{{ .Data.data.SPRING_DATASOURCE_URL }}"
          export SPRING_DATASOURCE_USERNAME="{{ .Data.data.SPRING_DATASOURCE_USERNAME }}"
          export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.SPRING_DATASOURCE_PASSWORD }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          export GOOGLE_CLIENT_ID="{{ .Data.data.GOOGLE_CLIENT_ID }}"
          export GOOGLE_CLIENT_SECRET="{{ .Data.data.GOOGLE_CLIENT_SECRET }}"
          export VITE_FRONTEND_URL="https://blog.nilm.cc"
          {{- end }}
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: blog-backend
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: blog-backend
          image: harbor.nilm.cc/blog/blog-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 128m
              memory: 512Mi
            limits:
              cpu: 1024m
              memory: 1024Mi
          ports:
            - containerPort: 8080
              name: blog-backend
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
          command: ["/bin/sh"]
          args: ["-c", "source /vault/secrets/dotenv; java -jar /app/app.jar"]
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blog-backend-service
spec:
  selector:
    app: blog-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: blog-backend
