apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base
  - namespace.yaml
  - vault-service-account.yaml

images:
  - name: blog
    newTag: dev-latest
