apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: blog
    newTag: dev-latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: blog-backend
      spec:
        template:
          metadata:
            annotations:
              vault.hashicorp.com/agent-inject-secret-dotenv: "blog-dev/data/app"
              vault.hashicorp.com/agent-inject-template-dotenv: |
                {{- with secret "blog-dev/data/app" -}}
                export SPRING_DATASOURCE_URL="{{ .Data.data.SPRING_DATASOURCE_URL }}"
                export SPRING_DATASOURCE_USERNAME="{{ .Data.data.SPRING_DATASOURCE_USERNAME }}"
                export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.SPRING_DATASOURCE_PASSWORD }}"
                export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
                export GOOGLE_CLIENT_ID="{{ .Data.data.GOOGLE_CLIENT_ID }}"
                export GOOGLE_CLIENT_SECRET="{{ .Data.data.GOOGLE_CLIENT_SECRET }}"
                export VITE_FRONTEND_URL="https://blog-dev.nilm.cc"
                export MINIO_ENDPOINT="{{ .Data.data.MINIO_ENDPOINT }}"
                export MINIO_ACCESS_KEY="{{ .Data.data.MINIO_ACCESS_KEY }}"
                export MINIO_SECRET_KEY="{{ .Data.data.MINIO_SECRET_KEY }}"
                export MINIO_BUCKET_NAME="{{ .Data.data.MINIO_BUCKET_NAME }}"
                {{- end }}
              vault.hashicorp.com/tls-skip-verify: "true"
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: blog-ingress
      spec:
        tls:
          - hosts:
              - blog-dev.nilm.cc
            secretName: blog-vault-tls # cert-manager會自動創建這個Secret
        rules:
          - host: blog-dev.nilm.cc
            http:
              paths:
                - path: /api
                  pathType: Prefix
                  backend:
                    service:
                      name: blog-backend-service
                      port:
                        number: 8080
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: blog-frontend-service
                      port:
                        number: 80
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: blog-vault-cert
      spec:
        commonName: blog-dev.nilm.cc
        dnsNames:
          - blog-dev.nilm.cc
